services:
    db:
        image: postgres:17-alpine
        environment:
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=home
        expose:
            - 5432
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
